// ts/main.ts
import { AudioController } from "./audio_controller";
import { DisplayController, Status } from "./display_controller";
import { ScheduleEditor } from "./schedule/editor/schedule_editor";
import {
  registerCategory,
  getCategory,
  getAvailableCategories,
  getDefaultGlobalSettingsForCategory,
} from "./feature_registry";
import { SettingsUISchemaItem, Feature } from "./feature";
import { GuitarCategory } from "./guitar/guitar_category";
import {
  AppSettings,
  loadSettings,
  CategorySettingsMap,
  SETTINGS_STORAGE_KEY,
  LAST_RUN_SCHEDULE_JSON_KEY,
  RECENT_SCHEDULES_JSON_KEY,
  MAX_RECENT_SCHEDULES,
} from "./settings";
import { ScheduleLoadModal } from "./schedule/schedule_load_modal";
import { Schedule } from "./schedule/schedule";

import { FloatingViewManager } from './floating_views/floating_view_manager';
import { getAvailableFloatingViews, registerFloatingView } from './floating_views/floating_view_registry';
import { SettingsManager } from "./settings_manager";
import { TimerView } from "./views/timer_view";
import { ScheduleTimerView } from "./views/schedule_timer_view";
import { SchedulePlaybackView } from "./views/schedule_playback_view";

// --- Constants ---
const DEFAULT_MAX_CANVAS_HEIGHT = 650;
const CATEGORY_SETTINGS_CONTAINER_ID = "category-settings-container";

export class Main {
  currentSchedule: Schedule | null = null;
  displayController!: DisplayController;
  audioController!: AudioController;
  scheduleEditor!: ScheduleEditor;
  scheduleLoadModal!: ScheduleLoadModal;
  floatingViewManager!: FloatingViewManager;
  inlineTimerView!: TimerView;
  scheduleTimerView!: ScheduleTimerView;

  // UI Elements
  settingsButtonEl!: HTMLElement;
  floatingViewDropdownContainerEl!: HTMLElement;
  floatingViewDropdownContentEl!: HTMLElement;
  scheduleAccordionEl!: HTMLElement;
  scheduleAccordionHeaderEl!: HTMLElement;
  loadScheduleButtonEl!: HTMLElement;

  settings: AppSettings;
  settingsManager!: SettingsManager;

  constructor() {
    console.log("Initializing Main Application...");

    // --- Register Categories ---
    registerCategory(new GuitarCategory());

    // Register floating timer view (standalone mode – no schedule callbacks)
    registerFloatingView({
      viewId: "floating_timer",
      displayName: "Timer",
      categoryName: "General",
      defaultWidth: 300,
      defaultHeight: 150,
      createView: (initialState?: any) => new TimerView(initialState?.duration ?? 300),
    });

    // Load settings - uses the now-populated registry for defaults
    this.settings = loadSettings();

    // --- Instantiate Managers ---
    this.floatingViewManager = new FloatingViewManager(this.settings, 'floatingViewStates_practice');
    this.settingsManager = new SettingsManager(this.settings, 'practice', (newSettings) => {
        this.saveSettings(newSettings);
        this.applySettings();
        this.reset();
    });

    this.applySettings();

    // Create ScheduleTimerView FIRST — it renders #start-control, #settings-button, etc.
    // into #task-wrapper so ensureElementsExist() can find them.
    const taskWrapperEl = document.querySelector('#task-wrapper') as HTMLElement;
    if (!taskWrapperEl) {
      console.error("CRITICAL: #task-wrapper not found.");
      return;
    }
    this.scheduleTimerView = new ScheduleTimerView(taskWrapperEl, {
      onStartPause: () => this.toggleCountdown(),
      onSkip: () => this.skipCurrentTask(),
      onReset: () => this.reset(),
      onSettings: () => this.openSettingsModal(),
    });

    if (!this.ensureElementsExist()) return;

    // Assign dropdown elements (generated by ScheduleTimerView above)
    this.floatingViewDropdownContainerEl = document.querySelector('#floating-view-dropdown-container') as HTMLElement;
    this.floatingViewDropdownContentEl = document.querySelector('#floating-view-dropdown-content') as HTMLElement;

    // Initialize Controllers
    this.audioController = new AudioController(
      document.querySelector("#intro-end-sound") as HTMLAudioElement,
      document.querySelector("#interval-end-sound") as HTMLAudioElement,
      document.querySelector("#metronome-sound") as HTMLAudioElement,
      document.querySelector("#metronome-accent-sound") as HTMLAudioElement
    );
    this.displayController = new DisplayController(
      document.querySelector("#diagram") as HTMLElement,
      document.querySelector("#start-control") as HTMLElement,
    );

    // Create SchedulePlaybackView and wire it to DisplayController
    const playbackContainer = document.querySelector('#playback-view-container') as HTMLElement;
    const playbackView = new SchedulePlaybackView(playbackContainer);
    this.displayController.setPlaybackView(playbackView);

    // Create and wire the inline TimerView (schedule-driven mode)
    this.inlineTimerView = new TimerView(
      300,
      () => this.toggleCountdown(),
      () => this.reset(),
      (seconds) => this.currentSchedule?.setCurrentIntervalTime(seconds)
    );
    this.inlineTimerView.render(playbackView.getTimerContainer());
    this.displayController.setTimerView(this.inlineTimerView);

    // Initialize Schedule Editor
    const editorContainer = document.querySelector(
      "#schedule-editor-container"
    );
    if (editorContainer) {
      this.scheduleEditor = new ScheduleEditor(
        editorContainer as HTMLElement,
        () => this.reset(),
        this.audioController
      );
    } else {
      console.error("CRITICAL: Schedule editor container not found!");
      alert("Error: Schedule editor failed to load.");
      return;
    }

    // Initialize Load/Save Modal
    const loadModalElement = document.querySelector(
      "#load-schedule-modal"
    ) as HTMLElement;
    if (loadModalElement && this.scheduleEditor) {
      this.scheduleLoadModal = new ScheduleLoadModal(
        loadModalElement,
        this.scheduleEditor,
        RECENT_SCHEDULES_JSON_KEY
      );
      console.log("ScheduleLoadModal initialized.");
    } else {
      console.warn(
        "Load schedule modal element or ScheduleEditor not found. Load functionality unavailable."
      );
    }

    this.addControlHandlers();
    this.addAccordionHandlers();
    this.addFloatingViewDropdownHandlers();

    // --- Restore Floating Views AFTER manager is initialized ---
    this.floatingViewManager.restoreViewsFromState();

    // Load last run schedule
    let loadedFromStorage = false;
    const lastRunJSON = localStorage.getItem(LAST_RUN_SCHEDULE_JSON_KEY);
    if (lastRunJSON) {
      try {
        console.log(
          "Found last run schedule (JSON) in localStorage. Attempting to load..."
        );
        this.scheduleEditor.setScheduleJSON(lastRunJSON, true);
        loadedFromStorage = true;
        console.log(
          "Last run schedule (JSON) loaded successfully into editor."
        );
        this.reset();
      } catch (e: any) {
        console.error("Error loading or setting last run schedule JSON:", e);
        localStorage.removeItem(LAST_RUN_SCHEDULE_JSON_KEY);
        this.reset();
      }
    }

    if (!loadedFromStorage) {
      console.log(
        "No last run schedule JSON found or loading failed. Performing initial reset."
      );
      this.reset();
    }

    console.log("Initialization complete.");
  }

  private ensureElementsExist(): boolean {
    const requiredIds = [
      // Core UI
      "#diagram", "#playback-view-container", "#task-wrapper",
      // Audio
      "#intro-end-sound", "#interval-end-sound", "#metronome-sound", "#metronome-accent-sound",
      // Editor & Name
      "#schedule-editor-container", "#schedule-accordion",
      "#schedule-name-display", "#edit-schedule-name-btn",
      // Settings Modal Core
      "#settings-button",
      // Load/save modal (Optional check)
      "#load-schedule-button", "#load-schedule-modal",
      // Floating Views
      '#floating-view-button',
      '#floating-view-area',
      '#floating-view-dropdown-container',
      '#floating-view-dropdown-content',
    ];
    let allFound = true;
    requiredIds.forEach((id) => {
      const element = document.querySelector(id);
      if (!element) {
        if (id === "#load-schedule-modal" || id === "#load-schedule-button") {
          console.warn(`Optional HTML element not found: ${id}. Load/Save functionality might be unavailable.`);
        } else if (id === "#schedule-name-display" || id === "#edit-schedule-name-btn") {
          console.warn(`Optional HTML element not found: ${id}. Schedule naming UI disabled.`);
        } else if (id === '#floating-view-button' || id === '#floating-view-area' || id === '#floating-view-dropdown-container' || id === '#floating-view-dropdown-content') {
           console.warn(`Optional HTML element not found: ${id}. Floating view functionality might be unavailable.`);
        } else {
          console.error(`CRITICAL ERROR: Required HTML element not found: ${id}`);
          allFound = false;
        }
      }
    });

    if (allFound) {
      this.scheduleAccordionEl = document.querySelector("#schedule-accordion") as HTMLElement;
      this.scheduleAccordionHeaderEl = this.scheduleAccordionEl.querySelector(".accordion-header") as HTMLElement;
      this.loadScheduleButtonEl = document.querySelector("#load-schedule-button") as HTMLElement;

      if (this.scheduleAccordionEl && !this.scheduleAccordionHeaderEl) {
        console.error("CRITICAL ERROR: Accordion header not found inside accordion element.");
        allFound = false;
      }
    }

    if (!allFound) {
       alert("Error: Some required page elements could not be found. The application might not work correctly.");
    }
    return allFound;
  }

  addControlHandlers(): void {
    // Note: START/SKIP/RESET/SETTINGS buttons are now wired by ScheduleTimerView.
    // This method handles remaining controls (load-schedule modal button).
    this.settingsButtonEl = document.querySelector("#settings-button") as HTMLElement;
    this.loadScheduleButtonEl = document.querySelector("#load-schedule-button") as HTMLElement;

    if (this.loadScheduleButtonEl && this.scheduleLoadModal) {
      this.loadScheduleButtonEl.onclick = () => {
        if (this.currentSchedule?.isRunning()) {
          alert("Please stop the timer before loading or saving schedules.");
          return;
        }
        this.scheduleLoadModal.show();
      };
    } else if (this.loadScheduleButtonEl) {
      this.loadScheduleButtonEl.setAttribute("disabled", "true");
      this.loadScheduleButtonEl.setAttribute("title", "Load modal failed to initialize.");
    }
  }

  private addFloatingViewDropdownHandlers(): void {
    const floatingViewButtonEl = document.querySelector('#floating-view-button') as HTMLElement;
    if (!floatingViewButtonEl || !this.floatingViewDropdownContainerEl) {
        console.warn("Floating view button or dropdown container not found, handler not attached.");
        return;
    }

    floatingViewButtonEl.onclick = (event) => {
        event.stopPropagation();
        const isActive = this.floatingViewDropdownContainerEl.classList.toggle('is-active');
        if (isActive) {
            this.populateFloatingViewDropdown();
            document.addEventListener('click', this.handleClickOutsideDropdown, true);
        } else {
             document.removeEventListener('click', this.handleClickOutsideDropdown, true);
        }
    };
  }

  private handleClickOutsideDropdown = (event: MouseEvent): void => {
      if (this.floatingViewDropdownContainerEl && !this.floatingViewDropdownContainerEl.contains(event.target as Node)) {
          this.floatingViewDropdownContainerEl.classList.remove('is-active');
          document.removeEventListener('click', this.handleClickOutsideDropdown, true);
      }
  }

  private populateFloatingViewDropdown(): void {
       if (!this.floatingViewDropdownContentEl) return;

       this.floatingViewDropdownContentEl.innerHTML = '';
       const availableViews = getAvailableFloatingViews().filter(v => v.showInMenu !== false);

       if (availableViews.length === 0) {
           const noViewsItem = document.createElement('p');
           noViewsItem.classList.add('dropdown-item', 'is-size-7', 'has-text-grey');
           noViewsItem.textContent = 'No views available';
           this.floatingViewDropdownContentEl.appendChild(noViewsItem);
           return;
       }

       availableViews.forEach(desc => {
           const viewId = desc.viewId;
           const displayName = desc.displayName;
           const categoryName = desc.categoryName;

           const dropdownItem = document.createElement('a');
           dropdownItem.classList.add('dropdown-item');
           dropdownItem.href = "#";

           const itemText = document.createElement('span');
           itemText.textContent = displayName;

           const categorySpan = document.createElement('span');
           categorySpan.textContent = ` (${categoryName})`;
           categorySpan.classList.add('is-size-7', 'has-text-grey', 'ml-1');

           dropdownItem.appendChild(itemText);
           dropdownItem.appendChild(categorySpan);

           dropdownItem.onclick = (e) => {
               e.preventDefault();
               console.log(`Spawning view: ${viewId}`);
               this.floatingViewManager.spawnView(viewId);
               this.floatingViewDropdownContainerEl.classList.remove('is-active');
               document.removeEventListener('click', this.handleClickOutsideDropdown, true);
           };

           this.floatingViewDropdownContentEl.appendChild(dropdownItem);
       });
  }

  private saveSettings(newSettings: AppSettings): void {
      try {
        localStorage.setItem(SETTINGS_STORAGE_KEY, JSON.stringify(newSettings));
        this.settings = newSettings;
        if (this.floatingViewManager) {
            this.floatingViewManager.applySettingsChange(newSettings);
        }
      } catch (e) {
        console.error("Failed to save settings to localStorage:", e);
        alert("Error saving settings.");
      }
   }

  private applySettings(): void {
    if (this.settings.theme === "dark") {
      document.body.classList.add("dark-theme");
    } else {
      document.body.classList.remove("dark-theme");
    }
    console.log("Global settings applied.");
  }

  private openSettingsModal(): void {
    if (this.currentSchedule?.isRunning()) {
      alert("Please stop the timer before changing settings.");
      return;
    }
    this.settingsManager.open();
  }

  private addAccordionHandlers(): void {
    if (!this.scheduleAccordionHeaderEl) return;
    this.scheduleAccordionHeaderEl.onclick = () => {
      const isCollapsed = this.scheduleAccordionEl.classList.contains("collapsed");
      this.toggleScheduleAccordion(!isCollapsed);
    };
  }

  private toggleScheduleAccordion(collapse: boolean): void {
    if (!this.scheduleAccordionEl) return;
    this.scheduleAccordionEl.classList.toggle("collapsed", collapse);
  }

  toggleCountdown(): void {
    if (this.settingsManager.isOpen()) {
      console.warn("Settings modal is open.");
      return;
    }
    if (this.scheduleLoadModal?.isOpen()) {
      console.warn("Load Schedule modal is open.");
      return;
    }
    if (!this.currentSchedule) {
      this.reset();
      if (!this.currentSchedule) {
        console.error("Cannot start timer: Reset failed.");
        return;
      }
    }

    if (this.currentSchedule.isFinished()) {
      this.reset();
    } else if (this.currentSchedule.isRunning()) {
      this.currentSchedule.pause();
      this.toggleScheduleAccordion(false);
    } else {
      try {
        const scheduleJSON = this.scheduleEditor.getScheduleJSON();
        let isValidToSave = false;
        try {
          const parsed = JSON.parse(scheduleJSON);
          isValidToSave = parsed && Array.isArray(parsed.items) && parsed.items.length > 0;
        } catch {}
        if (isValidToSave) {
          localStorage.setItem(LAST_RUN_SCHEDULE_JSON_KEY, scheduleJSON);
          console.log("Saved current schedule as last run schedule (JSON).");
          const stored = localStorage.getItem(RECENT_SCHEDULES_JSON_KEY);
          let recentSchedules: string[] = [];
          if (stored) {
            try {
              const p = JSON.parse(stored);
              if (Array.isArray(p) && p.every((s) => typeof s === "string")) recentSchedules = p;
            } catch (e) { console.error(e); }
          }
          recentSchedules = recentSchedules.filter((item) => item !== scheduleJSON);
          recentSchedules.unshift(scheduleJSON);
          if (recentSchedules.length > MAX_RECENT_SCHEDULES) recentSchedules.length = MAX_RECENT_SCHEDULES;
          localStorage.setItem(RECENT_SCHEDULES_JSON_KEY, JSON.stringify(recentSchedules));
          if (this.scheduleLoadModal?.isOpen()) this.scheduleLoadModal.refreshRecentList();
        } else {
          console.log("Skipping save for empty or invalid schedule JSON.");
        }
      } catch (storageError) {
        console.error("Error saving schedule JSON to localStorage:", storageError);
      }
      this.currentSchedule.start();
      this.toggleScheduleAccordion(true);
    }
  }

  skipCurrentTask(): void {
    if (!this.currentSchedule || this.currentSchedule.isFinished()) {
      console.warn("Cannot skip: No active schedule or schedule finished.");
      return;
    }
    if (this.settingsManager.isOpen() || this.scheduleLoadModal?.isOpen()) {
      alert("Please close any open modals before skipping.");
      return;
    }
    this.currentSchedule.skip();
    this.toggleScheduleAccordion(this.currentSchedule.isRunning());
  }

  reset(): void {
    console.log("Resetting schedule using current editor state and settings...");
    this.currentSchedule?.pause();
    this.scheduleEditor?.errorDisplay?.removeMessage();

    try {
      const diagramContainer = document.getElementById("diagram");
      const maxCanvasHeight = diagramContainer?.clientHeight && diagramContainer.clientHeight > 50
        ? diagramContainer.clientHeight
        : DEFAULT_MAX_CANVAS_HEIGHT;

      this.currentSchedule = this.scheduleEditor.getSchedule(
        this.displayController,
        this.settings,
        maxCanvasHeight
      );

      if (this.currentSchedule && this.currentSchedule.intervals.length > 0) {
        this.currentSchedule.prepare();
        this.displayController.setStart();
        this.displayController.setStatus(Status.Pause);
        console.log("Schedule reset and prepared.");
      } else if (!this.scheduleEditor.errorDisplay.hasMessage()) {
        console.warn("Reset resulted in an empty schedule.");
        this.displayController.setTask("Load/Create Schedule", "lightgrey");
        this.displayController.setTime(0);
        this.displayController.setTotalTime(0, 0);
        this.displayController.setUpcoming([], true);
        this.displayController.setStatus(Status.Stop);
        this.displayController.setStart();
        this.displayController.clearFeature();
        this.currentSchedule = null;
      } else {
        console.error("Schedule reset failed due to errors during build.");
        this.displayController.setTask("Error During Build", "red");
        this.displayController.setTime(0);
        this.displayController.setTotalTime(0, 0);
        this.displayController.setUpcoming([], true);
        this.displayController.setStatus(Status.Stop);
        this.displayController.setStart();
        this.displayController.clearFeature();
        this.currentSchedule = null;
      }
    } catch (error) {
      console.error("Unexpected error during reset:", error);
      this.scheduleEditor?.errorDisplay?.showMessage(`Unexpected reset error: ${error}`);
      this.displayController.setTask("Unexpected Error", "red");
      this.displayController.setTime(0);
      this.displayController.setTotalTime(0, 0);
      this.displayController.setUpcoming([], true);
      this.displayController.setStatus(Status.Stop);
      this.displayController.setStart();
      this.displayController.clearFeature();
      this.currentSchedule = null;
    }
    this.toggleScheduleAccordion(false);
  }
}

// --- App Initialization ---
function initializeApp() {
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", () => new Main());
  } else {
    new Main();
  }
}
initializeApp();
